title: dOS
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Copyright (c) 2024 Daniel Ridner
baseurl: # the subpath of your site, e.g. /blog
url: "https://danielrid.github.io/dOS" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  
minima:
  skin: dark
  
header_pages:
  - about.md 
  
  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
